### ISSUE TITLE
nginx_server_block doesn't create config file

### ISSUE THREAD

**Issue by songmeo** [getstackhead/terraform-nginx#3]
I have nginx_server_block config like below:

```
resource "nginx_server_block" "my-server" {
  filename = "test.conf"
  enable = true
  markers = {
    docker_ports = "docker_container.nginx.web1.ports.external,docker_container.nginx.web2.ports.external"
  }
  markers_split = {
    docker_ports = ","
  }
  content = <<EOF
# external docker port is: {# docker_port #}
EOF
}
~
```

but when I run it gave:
```
│ Error: open /etc/nginx/sites-available/test.conf: no such file or directory
│
│   with nginx_server_block.my-server,
│   on nginx.tf line 1, in resource "nginx_server_block" "my-server":
│    1: resource "nginx_server_block" "my-server" {
│
```
Shouldn't `test.conf` be created?

**Comment by songmeo** [comment]
I checked inside container and there was no `sites-enabled` or `sites-available`. Here is the docker.tf file 
```
provider "docker" {}

resource "docker_image" "nginx" {
  name         = "nginx:latest"
  keep_locally = false
}

resource "docker_container" "nginx" {
  count = local.instance_count
  image = docker_image.nginx.latest
  name  = "web${count.index + 1}"
  ports {
    internal = 80
    external = "808${count.index + 1}"
  }
  volumes {
    container_path = "/usr/share/nginx/html"
    host_path      = "/tmp/me0w/www"
    read_only      = true
  }
}
```

**Comment by saitho** [comment]
Hi there,

the use of this provider is to create Nginx server configuration for a
locally running webserver where Terraform is executed.

The container_ports option is for creating reverse proxy configurations to
the ports of those containers. Per default the generated config is not
mounted into other Nginx containers - you'd have to do that yourself.

Also I think this uses the possibly old Nginx folder structure at
`/etc/nginx/sites-available`
which I have on my webserver (newer should be `/etc/nginx/config.d/` or
something like that). If so, the module is not compatible with those builds
of Nginx right now. I have no plans on adding that at the moment, only when
I need it myself.

Sorry I can't give you a more detailed answer right now, I've just gone on
vacation. ^^

Song Meo ***@***.***> schrieb am So., 22. Aug. 2021, 11:48:

**Comment by songmeo** [comment]
okay, it confirms my understanding then.
